spring:
  config:
    activate:
      on-profile: local

  # ==============================
  # DB 설정 (MariaDB + p6spy) - Local
  # ==============================
  datasource:
    # p6spy 사용 시 필수 드라이버
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    # 로컬 DB
    url: jdbc:p6spy:mariadb://203.245.44.21:3306/ehfqntuqntu

    # DB 계정 정보 (환경변수로 주입)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    dbcp2:
      default-auto-commit: false

  # ==============================
  # 파일 업로드 경로 - Local
  # ==============================
  servlet:
    multipart:
      # location: D:/files/nextjs_shop
      location: ${UPLOAD_DIR:D:/files/nextjs_shop}
